FROM rnburn/envoy-jaeger:0.14

WORKDIR /app

ADD . /app

RUN  apt-get update \
  && apt-get install --no-install-recommends --no-install-suggests -y \
              python-pip \
              python-dev \
              build-essential \
              python-setuptools \
              gettext \
              vim \
              gdb
RUN pip install -r requirements.txt

EXPOSE 8080
EXPOSE 8001
EXPOSE 8002
EXPOSE 8003

ENTRYPOINT /app/start_back.sh
